import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Search for PG',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='overflow-x-hidden'>{children}</body>
    </html>
  )
}
